### ISSUE TITLE
请问在多人视频会议时，能支持管理员将某个会议成员的视频窗口 显示在所有成员 的会议窗口之上么？

### ISSUE THREAD

**Issue by zhangshuling** [hankersyan/cordova-plugin-rtc-qiniu#1]
例如 A ,B,C,D 4位会议成员， A 为 管理员， 能随便设置 B,C,D为发言人， 例如此时 设置的发言人为 B ， 那么ABCD的会议界面上，看到的 全是 B 成员，或者将B 成员的摄像头图像 在每个人的 九空格显示的 界面 重点突出一下

**Comment by hankersyan** [comment]
暂时没此功能，可以转发给七牛云
