### ISSUE TITLE
你好，请问一下在做ionic3时，Android 使用这个插件没问题，但是IOS一直会错

### ISSUE THREAD

**Issue by zhangshuling** [hankersyan/cordova-plugin-rtc-qiniu#2]
ld: warning: directory not found for option '-L/Users/schoolwisdoms/Library/Developer/Xcode/DerivedData/demo-dzctiurjpwhvttesrifbjptedjly/Build/Products/Debug-iphonesimulator/Bugsnag'
ld: warning: directory not found for option '-L/Users/schoolwisdoms/Library/Developer/Xcode/DerivedData/demo-dzctiurjpwhvttesrifbjptedjly/Build/Products/Debug-iphonesimulator/JGProgressHUD'
ld: warning: directory not found for option '-L/Users/schoolwisdoms/Library/Developer/Xcode/DerivedData/demo-dzctiurjpwhvttesrifbjptedjly/Build/Products/Debug-iphonesimulator/MMMaterialDesignSpinner'
ld: warning: directory not found for option '-L/Users/schoolwisdoms/Library/Developer/Xcode/DerivedData/demo-dzctiurjpwhvttesrifbjptedjly/Build/Products/Debug-iphonesimulator/Masonry'

编译通不过，这几个目录 我就算直接从 /platforms/ios/Pods/Headers/Public 里面复制过去，也一样会报错，请问这是什么原因 啊？

在Profile 里面  加入下面的 配置 手动安装 ，最后xcode里面打包 仍然是上面的问题，求解啊
	pod 'Bugsnag', '~> 5.15.4'
	pod 'PLPlayerKit', '~> 3.4.1'
	pod 'MMMaterialDesignSpinner', '~> 0.2.5'
	pod 'JGProgressHUD', '~> 2.0.3'
	pod 'Masonry', '~> 1.1.0'

即时用网上说法最多的做法：
```
在Build Settings
Header Search Paths
Other Linker Flags
Preprocessor Macros
在这三个地方都加上$(inherited)，然后重新pod install就可以了
```
依然不行啊

**Comment by hankersyan** [comment]
用真机，别用模拟器simulator，由于lib库太大，把x86架构删除了。

**Comment by zhangshuling** [comment]
> 用真机，别用模拟器simulator，由于lib库太大，把x86架构删除了。

我现在是直接用的打包模式编译的，我有两个APP , 里面的所有配置全部都是一样的，但是两个工程编译打包的时候，一个工程是成功的，另一个工程是失败的，一直报
`
Undefined symbols for architecture arm64:
  _OBJC_CLASS_$_CDVUIWebViewDelegate, referenced from: objc-class-ref in CDVUIInAppBrowser.o
ld: symbol(s) not found for architecture arm64

`
如果卸载cordova-plugin-rtc-qiniu插件再编译就好了，虽然这个报错里面的两个文件，都跟cordova-plugin-rtc-qiniu没有关系，网上的很多方法都试过了 ....

**Comment by zhangshuling** [comment]
已经ok了，虽然两个app的配置是一样的，但是pod install 后生成的文件。经过手动改过，改出了一点点小问题，经过我长期反复的对比，终于发现问题了
